services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: cup_survey
      POSTGRES_PASSWORD: cup_survey
      POSTGRES_DB: cup_survey
    ports:
      - '5433:5432'
    volumes:
      - cup_survey_pg:/var/lib/postgresql/data

volumes:
  cup_survey_pg:
